class hclBendLinkConstraintSetMxSingle(object):
    bendMinLength: float
    stretchMaxLength: float
    stretchStiffness: float
    bendStiffness: float
    invMassA: float
    invMassB: float
    particleA: int
    particleB: int
