class hclBendStiffnessConstraintSetMxSingle(object):
    weightA: float
    weightB: float
    weightC: float
    weightD: float
    bendStiffness: float
    restCurvature: float
    invMassA: float
    invMassB: float
    invMassC: float
    invMassD: float
    particleA: int
    particleB: int
    particleC: int
    particleD: int
