from .hclBoneSpaceSkinOperator import hclBoneSpaceSkinOperator
from .hclBoneSpaceDeformerLocalBlockPNTB import hclBoneSpaceDeformerLocalBlockPNTB
from .hclBoneSpaceDeformerLocalBlockUnpackedPNTB import hclBoneSpaceDeformerLocalBlockUnpackedPNTB


class hclBoneSpaceSkinPNTBOperator(hclBoneSpaceSkinOperator):
	localPNTBs: hclBoneSpaceDeformerLocalBlockPNTB
	localUnpackedPNTBs: hclBoneSpaceDeformerLocalBlockUnpackedPNTB
