from .hclBoneSpaceSkinOperator import hclBoneSpaceSkinOperator
from .hclBoneSpaceDeformerLocalBlockP import hclBoneSpaceDeformerLocalBlockP
from .hclBoneSpaceDeformerLocalBlockUnpackedP import hclBoneSpaceDeformerLocalBlockUnpackedP


class hclBoneSpaceSkinPOperator(hclBoneSpaceSkinOperator):
    localPs: hclBoneSpaceDeformerLocalBlockP
    localUnpackedPs: hclBoneSpaceDeformerLocalBlockUnpackedP
