class hclBendLinkConstraintSetMxBatch(object):
    bendMinLengths: float
    stretchMaxLengths: float
    stretchStiffnesses: float
    bendStiffnesses: float
    invMassesA: float
    invMassesB: float
    particlesA: int
    particlesB: int
