class hclBendStiffnessConstraintSetMxBatch(object):
    weightsA: float
    weightsB: float
    weightsC: float
    weightsD: float
    bendStiffnesses: float
    restCurvatures: float
    invMassesA: float
    invMassesB: float
    invMassesC: float
    invMassesD: float
    particlesA: int
    particlesB: int
    particlesC: int
    particlesD: int
