from .hclConstraintSet import hclConstraintSet
from .hclCompressibleLinkConstraintSetLink import hclCompressibleLinkConstraintSetLink


class hclCompressibleLinkConstraintSet(hclConstraintSet):
    links: hclCompressibleLinkConstraintSetLink
