from .hclObjectSpaceSkinOperator import hclObjectSpaceSkinOperator
from .hclObjectSpaceDeformerLocalBlockPNT import hclObjectSpaceDeformerLocalBlockPNT
from .hclObjectSpaceDeformerLocalBlockUnpackedPNT import hclObjectSpaceDeformerLocalBlockUnpackedPNT


class hclObjectSpaceSkinPNTOperator(hclObjectSpaceSkinOperator):
    localPNTs: hclObjectSpaceDeformerLocalBlockPNT
    localUnpackedPNTs: hclObjectSpaceDeformerLocalBlockUnpackedPNT
