from .hclObjectSpaceDeformerEightBlendEntryBlock import hclObjectSpaceDeformerEightBlendEntryBlock
from .hclObjectSpaceDeformerSevenBlendEntryBlock import hclObjectSpaceDeformerSevenBlendEntryBlock
from .hclObjectSpaceDeformerSixBlendEntryBlock import hclObjectSpaceDeformerSixBlendEntryBlock
from .hclObjectSpaceDeformerFiveBlendEntryBlock import hclObjectSpaceDeformerFiveBlendEntryBlock
from .hclObjectSpaceDeformerFourBlendEntryBlock import hclObjectSpaceDeformerFourBlendEntryBlock
from .hclObjectSpaceDeformerThreeBlendEntryBlock import hclObjectSpaceDeformerThreeBlendEntryBlock
from .hclObjectSpaceDeformerTwoBlendEntryBlock import hclObjectSpaceDeformerTwoBlendEntryBlock
from .hclObjectSpaceDeformerOneBlendEntryBlock import hclObjectSpaceDeformerOneBlendEntryBlock


class hclObjectSpaceDeformer(object):
	eightBlendEntries: hclObjectSpaceDeformerEightBlendEntryBlock
	sevenBlendEntries: hclObjectSpaceDeformerSevenBlendEntryBlock
	sixBlendEntries: hclObjectSpaceDeformerSixBlendEntryBlock
	fiveBlendEntries: hclObjectSpaceDeformerFiveBlendEntryBlock
	fourBlendEntries: hclObjectSpaceDeformerFourBlendEntryBlock
	threeBlendEntries: hclObjectSpaceDeformerThreeBlendEntryBlock
	twoBlendEntries: hclObjectSpaceDeformerTwoBlendEntryBlock
	oneBlendEntries: hclObjectSpaceDeformerOneBlendEntryBlock
	controlBytes: any
	startVertexIndex: int
	endVertexIndex: int
	batchSizeSpu: int
	partialWrite: bool
