from .hclObjectSpaceMeshMeshDeformOperator import hclObjectSpaceMeshMeshDeformOperator
from .hclObjectSpaceDeformerLocalBlockPNTB import hclObjectSpaceDeformerLocalBlockPNTB
from .hclObjectSpaceDeformerLocalBlockUnpackedPNTB import hclObjectSpaceDeformerLocalBlockUnpackedPNTB


class hclObjectSpaceMeshMeshDeformPNTBOperator(hclObjectSpaceMeshMeshDeformOperator):
	localPNTBs: hclObjectSpaceDeformerLocalBlockPNTB
	localUnpackedPNTBs: hclObjectSpaceDeformerLocalBlockUnpackedPNTB
