from .hclObjectSpaceSkinOperator import hclObjectSpaceSkinOperator
from .hclObjectSpaceDeformerLocalBlockP import hclObjectSpaceDeformerLocalBlockP
from .hclObjectSpaceDeformerLocalBlockUnpackedP import hclObjectSpaceDeformerLocalBlockUnpackedP


class hclObjectSpaceSkinPOperator(hclObjectSpaceSkinOperator):
    localPs: hclObjectSpaceDeformerLocalBlockP
    localUnpackedPs: hclObjectSpaceDeformerLocalBlockUnpackedP
