from .hclConstraintSet import hclConstraintSet
from .hclStretchLinkConstraintSetMxBatch import hclStretchLinkConstraintSetMxBatch
from .hclStretchLinkConstraintSetMxSingle import hclStretchLinkConstraintSetMxSingle


class hclStretchLinkConstraintSetMx(hclConstraintSet):
	batches: hclStretchLinkConstraintSetMxBatch
	singles: hclStretchLinkConstraintSetMxSingle
