from .hclStorageSetupMeshSectionSectionVertexChannel import hclStorageSetupMeshSectionSectionVertexChannel
from .common import any


class hclStorageSetupMeshSectionSectionVertexSelectionChannel(hclStorageSetupMeshSectionSectionVertexChannel):
    vertexIndices: any
