from .hclTransformSetUsageTransformTracker import hclTransformSetUsageTransformTracker


class hclTransformSetUsage(object):
	perComponentFlags: int
	perComponentTransformTrackers: hclTransformSetUsageTransformTracker
