from .hkReferencedObject import hkReferencedObject
from .hkaFootstepAnalysisInfo import hkaFootstepAnalysisInfo


class hkaFootstepAnalysisInfoContainer(hkReferencedObject):
	previewInfo: hkaFootstepAnalysisInfo
