from .hkReferencedObject import hkReferencedObject
from .hkaiSilhouetteGenerationParameters import hkaiSilhouetteGenerationParameters


class hkaiSilhouetteMerger(hkReferencedObject):
	mergeType: any
	mergeParams: hkaiSilhouetteGenerationParameters
