from .hkReferencedObject import hkReferencedObject
from .hkaiUserEdgeUtilsUserEdgeSetup import hkaiUserEdgeUtilsUserEdgeSetup


class hkaiUserEdgeSetupArray(hkReferencedObject):
	edgeSetups: hkaiUserEdgeUtilsUserEdgeSetup
