from .hkReferencedObject import hkReferencedObject
from .hkaiUserEdgeUtilsUserEdgePair import hkaiUserEdgeUtilsUserEdgePair


class hkaiUserEdgePairArray(hkReferencedObject):
	edgePairs: hkaiUserEdgeUtilsUserEdgePair
