class hkaiNavVolumeGenerationSettingsMergingSettings(object):
    nodeWeight: float
    edgeWeight: float
    estimateNewEdges: bool
    iterationsStabilizationThreshold: int
    slopeThreshold: float
    maxMergingIterations: int
    randomSeed: int
    multiplier: float
    useSimpleFirstMergePass: bool
