from .hkaDefaultAnimatedReferenceFrame import hkaDefaultAnimatedReferenceFrame


class hkaParameterizedAnimationReferenceFrame(hkaDefaultAnimatedReferenceFrame):
	parameterValues: any
	parameterTypes: any
