from .hkOffsetBitFieldStoragehkArrayunsignedinthkContainerHeapAllocator import hkOffsetBitFieldStoragehkArrayunsignedinthkContainerHeapAllocator


class hkBitFieldBasehkOffsetBitFieldStoragehkArrayunsignedinthkContainerHeapAllocator(object):
    storage: hkOffsetBitFieldStoragehkArrayunsignedinthkContainerHeapAllocator
