from .hkBitFieldStoragehkArrayunsignedinthkContainerHeapAllocator import hkBitFieldStoragehkArrayunsignedinthkContainerHeapAllocator


class hkBitFieldBasehkBitFieldStoragehkArrayunsignedinthkContainerHeapAllocator(object):
	storage: hkBitFieldStoragehkArrayunsignedinthkContainerHeapAllocator
