from .hkcdDynamicTreeTreehkcdDynamicTreeDynamicStoragePtr import hkcdDynamicTreeTreehkcdDynamicTreeDynamicStoragePtr


class hkcdDynamicTreeDefaultTreePtrStorage(hkcdDynamicTreeTreehkcdDynamicTreeDynamicStoragePtr):
