from .hkcdDynamicTreeAnisotropicMetric import hkcdDynamicTreeAnisotropicMetric
from .hkcdDynamicTreeCodecRawUlong import hkcdDynamicTreeCodecRawUlong


class hkcdDynamicTreeDynamicStorage0hkcdDynamicTreeAnisotropicMetrichkcdDynamicTreeCodecRawUlong(hkcdDynamicTreeAnisotropicMetric):
	nodes: hkcdDynamicTreeCodecRawUlong
	firstFree: int
