from .hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodecRawUint import hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodecRawUint


class hkcdDynamicTreeDynamicStorage32(hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodecRawUint):
    pass
