from .hkcdStaticTreeTreehkcdStaticTreeDynamicStorage32 import hkcdStaticTreeTreehkcdStaticTreeDynamicStorage32


class hkcdStaticTreeDefaultTreeStorage32(hkcdStaticTreeTreehkcdStaticTreeDynamicStorage32):
    pass
