from .hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis6 import hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis6


class hkcdStaticTreeDynamicStorage6(hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis6):
    pass
