from .hkcdStaticTreeTreehkcdStaticTreeDynamicStorage6 import hkcdStaticTreeTreehkcdStaticTreeDynamicStorage6


class hkcdStaticTreeDefaultTreeStorage6(hkcdStaticTreeTreehkcdStaticTreeDynamicStorage6):
    pass
