from .hkcdStaticTreeTreehkcdStaticTreeDynamicStorage5 import hkcdStaticTreeTreehkcdStaticTreeDynamicStorage5


class hkcdStaticTreeDefaultTreeStorage5(hkcdStaticTreeTreehkcdStaticTreeDynamicStorage5):
    pass
