from .hkcdDynamicTreeTreehkcdDynamicTreeDynamicStorageInt16 import hkcdDynamicTreeTreehkcdDynamicTreeDynamicStorageInt16


class hkcdDynamicTreeDefaultTreeInt16Storage(hkcdDynamicTreeTreehkcdDynamicTreeDynamicStorageInt16):
