from .hkcdStaticMeshTreeBasePrimitiveDataRunBaseunsignedshort import hkcdStaticMeshTreeBasePrimitiveDataRunBaseunsignedshort


class hkcdStaticMeshTreeDefaultDataRun(hkcdStaticMeshTreeBasePrimitiveDataRunBaseunsignedshort):
