from .hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodecRawUlong import hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodecRawUlong


class hkcdDynamicTreeDynamicStoragePtr(hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodecRawUlong):
