from .hkcdStaticTreeDynamicStoragehkcdStaticTreeCodecRaw import hkcdStaticTreeDynamicStoragehkcdStaticTreeCodecRaw


class hkcdStaticTreeDynamicStorage32(hkcdStaticTreeDynamicStoragehkcdStaticTreeCodecRaw):
