from .hkcdStaticMeshTreeBaseConnectivitySectionHeader import hkcdStaticMeshTreeBaseConnectivitySectionHeader


class hkcdStaticMeshTreeBaseConnectivity(object):
	headers: hkcdStaticMeshTreeBaseConnectivitySectionHeader
	localLinks: any
	globalLinks: any
