from .hkcdStaticTreeTreehkcdStaticTreeDynamicStorage4 import hkcdStaticTreeTreehkcdStaticTreeDynamicStorage4


class hkcdStaticTreeDefaultTreeStorage4(hkcdStaticTreeTreehkcdStaticTreeDynamicStorage4):
