from .hkcdDynamicTreeTreehkcdDynamicTreeDynamicStorage32 import hkcdDynamicTreeTreehkcdDynamicTreeDynamicStorage32


class hkcdDynamicTreeDefaultTree48Storage(hkcdDynamicTreeTreehkcdDynamicTreeDynamicStorage32):
    pass
