from .hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodec32 import hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodec32


class hkcdDynamicTreeDynamicStorage16(hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodec32):
