from .hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis5 import hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis5


class hkcdStaticTreeDynamicStorage5(hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis5):
    pass
