from .hkcdStaticMeshTreeBasePrimitiveDataRunBaseunsignedint import hkcdStaticMeshTreeBasePrimitiveDataRunBaseunsignedint


class hkpBvCompressedMeshShapeTreeDataRun(hkcdStaticMeshTreeBasePrimitiveDataRunBaseunsignedint):
    pass
