from .hkpConstraintData import hkpConstraintData
from .hkpBallAndSocketConstraintDataAtoms import hkpBallAndSocketConstraintDataAtoms


class hkpBallAndSocketConstraintData(hkpConstraintData):
	atoms: hkpBallAndSocketConstraintDataAtoms
