from .hkpSetLocalTransformsConstraintAtom import hkpSetLocalTransformsConstraintAtom
from .hkpCogWheelConstraintAtom import hkpCogWheelConstraintAtom


class hkpCogWheelConstraintDataAtoms(object):
	transforms: hkpSetLocalTransformsConstraintAtom
	cogWheels: hkpCogWheelConstraintAtom
