from .hkpConstraintData import hkpConstraintData
from .hkpDeformableFixedConstraintDataAtoms import hkpDeformableFixedConstraintDataAtoms


class hkpDeformableFixedConstraintData(hkpConstraintData):
	atoms: hkpDeformableFixedConstraintDataAtoms
