from .hkpEntitySmallArraySerializeOverrideType import hkpEntitySmallArraySerializeOverrideType


class hkpEntityExtendedListeners(object):
    activationListeners: hkpEntitySmallArraySerializeOverrideType
    entityListeners: hkpEntitySmallArraySerializeOverrideType
