from .hkpEntitySmallArraySerializeOverrideType import hkpEntitySmallArraySerializeOverrideType
from .hkpEntitySmallArraySerializeOverrideType import hkpEntitySmallArraySerializeOverrideType


class hkpEntityExtendedListeners(object):
	activationListeners: hkpEntitySmallArraySerializeOverrideType
	entityListeners: hkpEntitySmallArraySerializeOverrideType
