from .hkpSetLocalRotationsConstraintAtom import hkpSetLocalRotationsConstraintAtom
from .hkpAngLimitConstraintAtom import hkpAngLimitConstraintAtom
from .hkp2dAngConstraintAtom import hkp2dAngConstraintAtom


class hkpHingeLimitsDataAtoms(object):
	rotations: hkpSetLocalRotationsConstraintAtom
	angLimit: hkpAngLimitConstraintAtom
	2dAng: hkp2dAngConstraintAtom
