from .hkpConstraintData import hkpConstraintData
from .hkpLinearClearanceConstraintDataAtoms import hkpLinearClearanceConstraintDataAtoms


class hkpLinearClearanceConstraintData(hkpConstraintData):
	atoms: hkpLinearClearanceConstraintDataAtoms
