from .hkpConstraintData import hkpConstraintData
from .hkpPrismaticConstraintDataAtoms import hkpPrismaticConstraintDataAtoms


class hkpPrismaticConstraintData(hkpConstraintData):
	atoms: hkpPrismaticConstraintDataAtoms
