from .hkpSetLocalTranslationsConstraintAtom import hkpSetLocalTranslationsConstraintAtom
from .hkpPulleyConstraintAtom import hkpPulleyConstraintAtom


class hkpPulleyConstraintDataAtoms(object):
	translations: hkpSetLocalTranslationsConstraintAtom
	pulley: hkpPulleyConstraintAtom
