from .hkpConstraintData import hkpConstraintData
from .hkpRagdollConstraintDataAtoms import hkpRagdollConstraintDataAtoms


class hkpRagdollConstraintData(hkpConstraintData):
	atoms: hkpRagdollConstraintDataAtoms
