from .hkpSetLocalTransformsConstraintAtom import hkpSetLocalTransformsConstraintAtom
from .hkpRackAndPinionConstraintAtom import hkpRackAndPinionConstraintAtom


class hkpRackAndPinionConstraintDataAtoms(object):
    transforms: hkpSetLocalTransformsConstraintAtom
    rackAndPinion: hkpRackAndPinionConstraintAtom
