from .hkpConstraintData import hkpConstraintData
from .hkpRackAndPinionConstraintDataAtoms import hkpRackAndPinionConstraintDataAtoms


class hkpRackAndPinionConstraintData(hkpConstraintData):
	atoms: hkpRackAndPinionConstraintDataAtoms
