from .hkReferencedObject import hkReferencedObject
from .hkpSerializedDisplayMarker import hkpSerializedDisplayMarker


class hkpSerializedDisplayMarkerList(hkReferencedObject):
	markers: hkpSerializedDisplayMarker
