from .hkReferencedObject import hkReferencedObject
from .hkpSerializedDisplayRbTransformsDisplayTransformPair import hkpSerializedDisplayRbTransformsDisplayTransformPair


class hkpSerializedDisplayRbTransforms(hkReferencedObject):
	transforms: hkpSerializedDisplayRbTransformsDisplayTransformPair
