class hkpVehicleFrictionStatusAxisStatus(object):
    forward_slip_velocity: float
    side_slip_velocity: float
    skid_energy_density: float
    side_force: float
    delayed_forward_impulse: float
    sideRhs: float
    forwardRhs: float
    relativeSideForce: float
    relativeForwardForce: float
