from .hkReferencedObject import hkReferencedObject
from .hkpVehicleSuspensionSuspensionWheelParameters import hkpVehicleSuspensionSuspensionWheelParameters


class hkpVehicleSuspension(hkReferencedObject):
    wheelParams: hkpVehicleSuspensionSuspensionWheelParameters
