class hkpVehicleFrictionDescriptionAxisDescription(object):
    frictionCircleYtab: float
    xStep: float
    xStart: float
    wheelSurfaceInertia: float
    wheelSurfaceInertiaInv: float
    wheelChassisMassRatio: float
    wheelRadius: float
    wheelRadiusInv: float
    wheelDownForceFactor: float
    wheelDownForceSumFactor: float
