from .hkpVehicleSuspension import hkpVehicleSuspension
from .hkpVehicleDefaultSuspensionWheelSpringSuspensionParameters import hkpVehicleDefaultSuspensionWheelSpringSuspensionParameters


class hkpVehicleDefaultSuspension(hkpVehicleSuspension):
    wheelSpringParams: hkpVehicleDefaultSuspensionWheelSpringSuspensionParameters
