class hkpVehicleDataWheelComponentParams(object):
    radius: float
    mass: float
    width: float
    friction: float
    viscosityFriction: float
    maxFriction: float
    slipAngle: float
    forceFeedbackMultiplier: float
    maxContactBodyAcceleration: float
    axle: int
