from .hkpConstraintData import hkpConstraintData
from .hkpWheelFrictionConstraintDataAtoms import hkpWheelFrictionConstraintDataAtoms


class hkpWheelFrictionConstraintData(hkpConstraintData):
	atoms: hkpWheelFrictionConstraintDataAtoms
