class hkpWheelFrictionConstraintAtomAxle(object):
    spinVelocity: float
    sumVelocity: float
    numWheels: int
    wheelsSolved: int
    stepsSolved: int
    invInertia: float
    inertia: float
    impulseScaling: float
    impulseMax: float
    isFixed: bool
    numWheelsOnGround: int
