from .hkSetunsignedinthkContainerHeapAllocatorhkMapOperationsunsignedint import hkSetunsignedinthkContainerHeapAllocatorhkMapOperationsunsignedint


class hkSetUint32(hkSetunsignedinthkContainerHeapAllocatorhkMapOperationsunsignedint):
    pass
