from .hkSetunsignedlonglonghkContainerHeapAllocatorhkMapOperationsunsignedlonglong import hkSetunsignedlonglonghkContainerHeapAllocatorhkMapOperationsunsignedlonglong


class hkSetUint64(hkSetunsignedlonglonghkContainerHeapAllocatorhkMapOperationsunsignedlonglong):
